### ISSUE TITLE
LBFGSB still prints messages even with `iprint < 0`

### ISSUE THREAD

**Issue by bblankrot** [Gnimuc/LBFGSB.jl#9]
The underlying Fortran code still prints messages regardless of `iprint`, which clogs up stdout pretty quickly in my case. This could be fixed fairly quickly by adding an if statement to lines 3282-3283 in `lbfgsb.f`:
```fortran
write(6,*) ' Positive dir derivative in projection '
write(6,*) ' Using the backtracking step '
```
If this package uses the C version, the fix [is detailed here](https://github.com/Kitware/ITK/commit/e29bf9abb3f76871f8d726849a57fab70e6914e6). I'm not sure how to do it myself since I am unfamiliar with the new dependency-building mechanism.

**Comment by Gnimuc** [comment]
We can apply this patch to the upstream: https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/L-BFGS-B.

If it's not urgent, I'm going to fix it this weekend.

**Comment by bblankrot** [comment]
Not urgent at all, thanks a bunch!
